# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import vocabulary_pb2 as vocabulary__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vocabulary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VocabularyControllerStub(object):
    """CONTROLLERS

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrUpdateVocabulary = channel.unary_unary(
                '/vocabulary_app.VocabularyController/CreateOrUpdateVocabulary',
                request_serializer=vocabulary__pb2.Vocabulary.SerializeToString,
                response_deserializer=vocabulary__pb2.Vocabulary.FromString,
                _registered_method=True)
        self.CreateVocabularies = channel.stream_unary(
                '/vocabulary_app.VocabularyController/CreateVocabularies',
                request_serializer=vocabulary__pb2.Vocabulary.SerializeToString,
                response_deserializer=vocabulary__pb2.VocabulariesCreationResponse.FromString,
                _registered_method=True)
        self.GetVocabularies = channel.unary_stream(
                '/vocabulary_app.VocabularyController/GetVocabularies',
                request_serializer=vocabulary__pb2.VocabularyFilters.SerializeToString,
                response_deserializer=vocabulary__pb2.Vocabulary.FromString,
                _registered_method=True)
        self.GetVocabulary = channel.unary_unary(
                '/vocabulary_app.VocabularyController/GetVocabulary',
                request_serializer=vocabulary__pb2.VocabularyRequest.SerializeToString,
                response_deserializer=vocabulary__pb2.Vocabulary.FromString,
                _registered_method=True)


class VocabularyControllerServicer(object):
    """CONTROLLERS

    """

    def CreateOrUpdateVocabulary(self, request, context):
        """Create vocab.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVocabularies(self, request_iterator, context):
        """Create vocabularies with client side streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVocabularies(self, request, context):
        """filter vocabs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVocabulary(self, request, context):
        """get one vocabulary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VocabularyControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrUpdateVocabulary': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdateVocabulary,
                    request_deserializer=vocabulary__pb2.Vocabulary.FromString,
                    response_serializer=vocabulary__pb2.Vocabulary.SerializeToString,
            ),
            'CreateVocabularies': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateVocabularies,
                    request_deserializer=vocabulary__pb2.Vocabulary.FromString,
                    response_serializer=vocabulary__pb2.VocabulariesCreationResponse.SerializeToString,
            ),
            'GetVocabularies': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVocabularies,
                    request_deserializer=vocabulary__pb2.VocabularyFilters.FromString,
                    response_serializer=vocabulary__pb2.Vocabulary.SerializeToString,
            ),
            'GetVocabulary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVocabulary,
                    request_deserializer=vocabulary__pb2.VocabularyRequest.FromString,
                    response_serializer=vocabulary__pb2.Vocabulary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vocabulary_app.VocabularyController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vocabulary_app.VocabularyController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VocabularyController(object):
    """CONTROLLERS

    """

    @staticmethod
    def CreateOrUpdateVocabulary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocabulary_app.VocabularyController/CreateOrUpdateVocabulary',
            vocabulary__pb2.Vocabulary.SerializeToString,
            vocabulary__pb2.Vocabulary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVocabularies(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vocabulary_app.VocabularyController/CreateVocabularies',
            vocabulary__pb2.Vocabulary.SerializeToString,
            vocabulary__pb2.VocabulariesCreationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVocabularies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vocabulary_app.VocabularyController/GetVocabularies',
            vocabulary__pb2.VocabularyFilters.SerializeToString,
            vocabulary__pb2.Vocabulary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVocabulary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocabulary_app.VocabularyController/GetVocabulary',
            vocabulary__pb2.VocabularyRequest.SerializeToString,
            vocabulary__pb2.Vocabulary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WordControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrUpdateWord = channel.unary_unary(
                '/vocabulary_app.WordController/CreateOrUpdateWord',
                request_serializer=vocabulary__pb2.Word.SerializeToString,
                response_deserializer=vocabulary__pb2.Word.FromString,
                _registered_method=True)
        self.CreateWords = channel.stream_unary(
                '/vocabulary_app.WordController/CreateWords',
                request_serializer=vocabulary__pb2.Word.SerializeToString,
                response_deserializer=vocabulary__pb2.WordsCreationResponse.FromString,
                _registered_method=True)
        self.GetWords = channel.unary_stream(
                '/vocabulary_app.WordController/GetWords',
                request_serializer=vocabulary__pb2.WordFilters.SerializeToString,
                response_deserializer=vocabulary__pb2.Word.FromString,
                _registered_method=True)
        self.GetWord = channel.unary_unary(
                '/vocabulary_app.WordController/GetWord',
                request_serializer=vocabulary__pb2.WordRequest.SerializeToString,
                response_deserializer=vocabulary__pb2.Word.FromString,
                _registered_method=True)


class WordControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrUpdateWord(self, request, context):
        """Create word inside one vocabulary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWords(self, request_iterator, context):
        """Create words with client side streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWords(self, request, context):
        """filter words inside one vocab.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWord(self, request, context):
        """get one word inside one vocabulary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrUpdateWord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdateWord,
                    request_deserializer=vocabulary__pb2.Word.FromString,
                    response_serializer=vocabulary__pb2.Word.SerializeToString,
            ),
            'CreateWords': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateWords,
                    request_deserializer=vocabulary__pb2.Word.FromString,
                    response_serializer=vocabulary__pb2.WordsCreationResponse.SerializeToString,
            ),
            'GetWords': grpc.unary_stream_rpc_method_handler(
                    servicer.GetWords,
                    request_deserializer=vocabulary__pb2.WordFilters.FromString,
                    response_serializer=vocabulary__pb2.Word.SerializeToString,
            ),
            'GetWord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWord,
                    request_deserializer=vocabulary__pb2.WordRequest.FromString,
                    response_serializer=vocabulary__pb2.Word.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vocabulary_app.WordController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vocabulary_app.WordController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WordController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrUpdateWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocabulary_app.WordController/CreateOrUpdateWord',
            vocabulary__pb2.Word.SerializeToString,
            vocabulary__pb2.Word.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWords(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vocabulary_app.WordController/CreateWords',
            vocabulary__pb2.Word.SerializeToString,
            vocabulary__pb2.WordsCreationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vocabulary_app.WordController/GetWords',
            vocabulary__pb2.WordFilters.SerializeToString,
            vocabulary__pb2.Word.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vocabulary_app.WordController/GetWord',
            vocabulary__pb2.WordRequest.SerializeToString,
            vocabulary__pb2.Word.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
